flags: {}
packages:
- '.'
- location: ../Nomyx-Core
  extra-dep: true
- location: ../Nomyx-Language
  extra-dep: true
- location: ../Nomyx-Library
  extra-dep: true
- location: ../Nomyx-Auth
  extra-dep: true
- location: ../Imprevu
  extra-dep: true
- location: ../Imprevu-Happstack
  extra-dep: true
- location: ../shortcut
  extra-dep: true
extra-deps:
- Nomyx-Core-0.7.6
- Nomyx-Language-0.7.6
- Nomyx-Library-0.7.6
- DebugTraceHelpers-0.12
- time-recurrence-0.9.2
- zoom-refs-0.0.0.1
resolver: lts-5.11
